In [3]:
X = df.drop("class", axis=1)
y = df["class"]

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

num_features = ["purchase_value", "age", "ip_address", "time_since_signup", "hour_of_day", "day_of_week", "transaction_count", "ip_int"]
preprocessor = ColumnTransformer(
    transformers=[("num", StandardScaler(), num_features)],
    remainder="passthrough"  # leave bools as-is
)

In [9]:
# Features (X) and target (y)
X = df.drop(columns=["class", "user_id", "signup_time", "purchase_time", "device_id", "ip_address"])
y = df["class"]

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [11]:
from sklearn.model_selection import train_test_split

# Features and target
X = df.drop(columns=["class", "user_id", "signup_time", "purchase_time", "device_id", "ip_address"])  # keep only numeric / encoded features
y = df["class"]

# Stratified split to keep class imbalance consistent
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)

Training set size: (120889, 14)
Test set size: (30223, 14)

In [3]:
import os

def print_directory_tree(root_dir, indent=""):
    for item in os.listdir(root_dir):
        path = os.path.join(root_dir, item)
        if os.path.isdir(path):
            print(f"{indent}[DIR]  {item}")
            print_directory_tree(path, indent + "    ")
        else:
            print(f"{indent}[FILE] {item}")

# Change this to your project root folder
project_root = r"C:\Users\Yosef Maregn\Desktop\fraud-detection"
print_directory_tree(project_root)

[DIR]  .git
    [FILE] COMMIT_EDITMSG
    [FILE] config
    [FILE] description
    [FILE] FETCH_HEAD
    [FILE] HEAD
    [DIR]  hooks
        [FILE] applypatch-msg.sample
        [FILE] commit-msg.sample
        [FILE] fsmonitor-watchman.sample
        [FILE] post-update.sample
        [FILE] pre-applypatch.sample
        [FILE] pre-commit.sample
        [FILE] pre-merge-commit.sample
        [FILE] pre-push.sample
        [FILE] pre-rebase.sample
        [FILE] pre-receive.sample
        [FILE] prepare-commit-msg.sample
        [FILE] push-to-checkout.sample
        [FILE] sendemail-validate.sample
        [FILE] update.sample
    [FILE] index
    [DIR]  info
        [FILE] exclude
    [DIR]  logs
        [FILE] HEAD
        [DIR]  refs
            [DIR]  heads
                [DIR]  feature
                    [FILE] fraud-modeling
                [FILE] main
            [DIR]  remotes
                [DIR]  origin
                    [DIR]  feature
                        [FILE] fraud-modeling
                    [FILE] HEAD
                    [FILE] main
    [DIR]  objects
        [DIR]  03
            [FILE] a5f8dffc1e16c5979a825fc0439de3a4dc2166
        [DIR]  06
            [FILE] 419ac2b35b822a8bd6ef56b3b2918e0641ff7e
        [DIR]  08
            [FILE] a278a042e007f637215da7a09331630a429281
        [DIR]  0a
            [FILE] 6d59d492860e805fb237f1736c3ebba3018c51
        [DIR]  0d
            [FILE] 6695d3418ed2911203b4898416b4adb87caf68
        [DIR]  11
            [FILE] 9fa4712e2fda6eed8e48724491ffe34b5e5573
        [DIR]  1a
            [FILE] d09acefc98a48e433b93c7706ed3eeab8ea677
        [DIR]  1f
            [FILE] 8bff9cb132ed2010bba24d1532486c72d236f9
        [DIR]  28
            [FILE] 279c9cc1f490aedb9a21ef094414d4166ea9b0
        [DIR]  2e
            [FILE] 240346bddbe70f873efb9b81eff70650e7b826
        [DIR]  45
            [FILE] b852bf84b00bc057662d5f03f8b32eb2334a2e
        [DIR]  59
            [FILE] 306735e84c91b277d4b358854fb454046b8add
        [DIR]  7b
            [FILE] d8460029df0765116abdc596207af47ed8d780
        [DIR]  7f
            [FILE] e6751c9e430a178bd04fc9e0361602ce47309d
        [DIR]  83
            [FILE] d3dafd4ec16ffe64fe703b059a25148da22f23
        [DIR]  89
            [FILE] ef0358f3edbfe03ef05c8949e1f64c2a5e1a5e
        [DIR]  9c
            [FILE] 412b9dc32b4b1692829f0638e7ea8813a2c793
        [DIR]  9d
            [FILE] 1dcfdaf1a6857c5f83dc27019c7600e1ffaff8
        [DIR]  a3
            [FILE] 84eae3d164f99f5c28bc01f234bc656db04386
        [DIR]  ad
            [FILE] bb97d2d3137fe76f2d8e88a55e1c2b285a6cd6
        [DIR]  b3
            [FILE] db3d2c3d409a2172e542d4f248a6a6a1e0ffa2
        [DIR]  be
            [FILE] 227179dd8ea90d48a4a700b06020e0c9fcdc9b
        [DIR]  c2
            [FILE] 0d09d06b13fbbef9cd6101eb338ccb2a2a853a
        [DIR]  cf
            [FILE] c2f7bb0e3c2753a97a79735ad8092275b66817
        [DIR]  e6
            [FILE] 9de29bb2d1d6434b8b29ae775ad8c2e48c5391
        [DIR]  f2
            [FILE] 27a80e4015fdc1b100e32ec40cc1ac440fe6f3
        [DIR]  f5
            [FILE] d82746cc7035af2703cb043397c206b87d77a4
        [DIR]  f9
            [FILE] 3e3a1a1525fb5b91020da86e44810c87a2d7bc
        [DIR]  fb
            [FILE] 904a2903f93e4b35ec5979203c8d5bcc2f434f
        [DIR]  fe
            [FILE] 04509101853295565b651ad2374a1d5a595696
            [FILE] 11992682002384d71a40c97a2d948e7a125dc3
        [DIR]  info
        [DIR]  pack
    [FILE] ORIG_HEAD
    [DIR]  refs
        [DIR]  heads
            [DIR]  feature
                [FILE] fraud-modeling
            [FILE] main
        [DIR]  remotes
            [DIR]  origin
                [DIR]  feature
                    [FILE] fraud-modeling
                [FILE] HEAD
                [FILE] main
        [DIR]  tags
[DIR]  .github
    [DIR]  workflows
[FILE] .gitignore
[DIR]  .venv
    [FILE] .gitignore
    [DIR]  Include
    [DIR]  Lib
        [DIR]  site-packages
            [DIR]  contourpy
                [FILE] array.py
                [FILE] chunk.py
                [FILE] convert.py
                [FILE] dechunk.py
                [FILE] enum_util.py
                [FILE] py.typed
                [FILE] typecheck.py
                [FILE] types.py
                [DIR]  util
                    [FILE] bokeh_renderer.py
                    [FILE] bokeh_util.py
                    [FILE] data.py
                    [FILE] mpl_renderer.py
                    [FILE] mpl_util.py
                    [FILE] renderer.py
                    [FILE] _build_config.py
                    [FILE] __init__.py
                    [DIR]  __pycache__
                        [FILE] bokeh_renderer.cpython-313.pyc
                        [FILE] bokeh_util.cpython-313.pyc
                        [FILE] data.cpython-313.pyc
                        [FILE] mpl_renderer.cpython-313.pyc
                        [FILE] mpl_util.cpython-313.pyc
                        [FILE] renderer.cpython-313.pyc
                        [FILE] _build_config.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                [FILE] _contourpy.cp313-win_amd64.lib
                [FILE] _contourpy.cp313-win_amd64.pyd
                [FILE] _contourpy.pyi
                [FILE] _version.py
                [FILE] __init__.py
                [DIR]  __pycache__
                    [FILE] array.cpython-313.pyc
                    [FILE] chunk.cpython-313.pyc
                    [FILE] convert.cpython-313.pyc
                    [FILE] dechunk.cpython-313.pyc
                    [FILE] enum_util.cpython-313.pyc
                    [FILE] typecheck.cpython-313.pyc
                    [FILE] types.cpython-313.pyc
                    [FILE] _version.cpython-313.pyc
                    [FILE] __init__.cpython-313.pyc
            [DIR]  contourpy-1.3.3.dist-info
                [FILE] INSTALLER
                [FILE] LICENSE
                [FILE] METADATA
                [FILE] RECORD
                [FILE] WHEEL
            [DIR]  cycler
                [FILE] py.typed
                [FILE] __init__.py
                [DIR]  __pycache__
                    [FILE] __init__.cpython-313.pyc
            [DIR]  cycler-0.12.1.dist-info
                [FILE] INSTALLER
                [FILE] LICENSE
                [FILE] METADATA
                [FILE] RECORD
                [FILE] top_level.txt
                [FILE] WHEEL
            [DIR]  dateutil
                [FILE] easter.py
                [DIR]  parser
                    [FILE] isoparser.py
                    [FILE] _parser.py
                    [FILE] __init__.py
                    [DIR]  __pycache__
                        [FILE] isoparser.cpython-313.pyc
                        [FILE] _parser.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                [FILE] relativedelta.py
                [FILE] rrule.py
                [DIR]  tz
                    [FILE] tz.py
                    [FILE] win.py
                    [FILE] _common.py
                    [FILE] _factories.py
                    [FILE] __init__.py
                    [DIR]  __pycache__
                        [FILE] tz.cpython-313.pyc
                        [FILE] win.cpython-313.pyc
                        [FILE] _common.cpython-313.pyc
                        [FILE] _factories.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                [FILE] tzwin.py
                [FILE] utils.py
                [DIR]  zoneinfo
                    [FILE] dateutil-zoneinfo.tar.gz
                    [FILE] rebuild.py
                    [FILE] __init__.py
                    [DIR]  __pycache__
                        [FILE] rebuild.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                [FILE] _common.py
                [FILE] _version.py
                [FILE] __init__.py
                [DIR]  __pycache__
                    [FILE] easter.cpython-313.pyc
                    [FILE] relativedelta.cpython-313.pyc
                    [FILE] rrule.cpython-313.pyc
                    [FILE] tzwin.cpython-313.pyc
                    [FILE] utils.cpython-313.pyc
                    [FILE] _common.cpython-313.pyc
                    [FILE] _version.cpython-313.pyc
                    [FILE] __init__.cpython-313.pyc
            [DIR]  fontTools
                [FILE] afmLib.py
                [FILE] agl.py
                [FILE] annotations.py
                [DIR]  cffLib
                    [FILE] CFF2ToCFF.py
                    [FILE] CFFToCFF2.py
                    [FILE] specializer.py
                    [FILE] transforms.py
                    [FILE] width.py
                    [FILE] __init__.py
                    [DIR]  __pycache__
                        [FILE] CFF2ToCFF.cpython-313.pyc
                        [FILE] CFFToCFF2.cpython-313.pyc
                        [FILE] specializer.cpython-313.pyc
                        [FILE] transforms.cpython-313.pyc
                        [FILE] width.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                [DIR]  colorLib
                    [FILE] builder.py
                    [FILE] errors.py
                    [FILE] geometry.py
                    [FILE] table_builder.py
                    [FILE] unbuilder.py
                    [FILE] __init__.py
                    [DIR]  __pycache__
                        [FILE] builder.cpython-313.pyc
                        [FILE] errors.cpython-313.pyc
                        [FILE] geometry.cpython-313.pyc
                        [FILE] table_builder.cpython-313.pyc
                        [FILE] unbuilder.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                [DIR]  config
                    [FILE] __init__.py
                    [DIR]  __pycache__
                        [FILE] __init__.cpython-313.pyc
                [DIR]  cu2qu
                    [FILE] benchmark.py
                    [FILE] cli.py
                    [FILE] cu2qu.c
                    [FILE] cu2qu.cp313-win_amd64.pyd
                    [FILE] cu2qu.py
                    [FILE] errors.py
                    [FILE] ufo.py
                    [FILE] __init__.py
                    [FILE] __main__.py
                    [DIR]  __pycache__
                        [FILE] benchmark.cpython-313.pyc
                        [FILE] cli.cpython-313.pyc
                        [FILE] cu2qu.cpython-313.pyc
                        [FILE] errors.cpython-313.pyc
                        [FILE] ufo.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                        [FILE] __main__.cpython-313.pyc
                [DIR]  designspaceLib
                    [FILE] split.py
                    [FILE] statNames.py
                    [FILE] types.py
                    [FILE] __init__.py
                    [FILE] __main__.py
                    [DIR]  __pycache__
                        [FILE] split.cpython-313.pyc
                        [FILE] statNames.cpython-313.pyc
                        [FILE] types.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                        [FILE] __main__.cpython-313.pyc
                [DIR]  encodings
                    [FILE] codecs.py
                    [FILE] MacRoman.py
                    [FILE] StandardEncoding.py
                    [FILE] __init__.py
                    [DIR]  __pycache__
                        [FILE] codecs.cpython-313.pyc
                        [FILE] MacRoman.cpython-313.pyc
                        [FILE] StandardEncoding.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                [DIR]  feaLib
                    [FILE] ast.py
                    [FILE] builder.py
                    [FILE] error.py
                    [FILE] lexer.c
                    [FILE] lexer.cp313-win_amd64.pyd
                    [FILE] lexer.py
                    [FILE] location.py
                    [FILE] lookupDebugInfo.py
                    [FILE] parser.py
                    [FILE] variableScalar.py
                    [FILE] __init__.py
                    [FILE] __main__.py
                    [DIR]  __pycache__
                        [FILE] ast.cpython-313.pyc
                        [FILE] builder.cpython-313.pyc
                        [FILE] error.cpython-313.pyc
                        [FILE] lexer.cpython-313.pyc
                        [FILE] location.cpython-313.pyc
                        [FILE] lookupDebugInfo.cpython-313.pyc
                        [FILE] parser.cpython-313.pyc
                        [FILE] variableScalar.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                        [FILE] __main__.cpython-313.pyc
                [FILE] fontBuilder.py
                [FILE] help.py
                [DIR]  merge
                    [FILE] base.py
                    [FILE] cmap.py
                    [FILE] layout.py
                    [FILE] options.py
                    [FILE] tables.py
                    [FILE] unicode.py
                    [FILE] util.py
                    [FILE] __init__.py
                    [FILE] __main__.py
                    [DIR]  __pycache__
                        [FILE] base.cpython-313.pyc
                        [FILE] cmap.cpython-313.pyc
                        [FILE] layout.cpython-313.pyc
                        [FILE] options.cpython-313.pyc
                        [FILE] tables.cpython-313.pyc
                        [FILE] unicode.cpython-313.pyc
                        [FILE] util.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                        [FILE] __main__.cpython-313.pyc
                [DIR]  misc
                    [FILE] arrayTools.py
                    [FILE] bezierTools.c
                    [FILE] bezierTools.cp313-win_amd64.pyd
                    [FILE] bezierTools.py
                    [FILE] classifyTools.py
                    [FILE] cliTools.py
                    [FILE] configTools.py
                    [FILE] cython.py
                    [FILE] dictTools.py
                    [FILE] eexec.py
                    [FILE] encodingTools.py
                    [FILE] enumTools.py
                    [FILE] etree.py
                    [FILE] filenames.py
                    [DIR]  filesystem
                        [FILE] _base.py
                        [FILE] _copy.py
                        [FILE] _errors.py
                        [FILE] _info.py
                        [FILE] _osfs.py
                        [FILE] _path.py
                        [FILE] _subfs.py
                        [FILE] _tempfs.py
                        [FILE] _tools.py
                        [FILE] _walk.py
                        [FILE] _zipfs.py
                        [FILE] __init__.py
                        [DIR]  __pycache__
                            [FILE] _base.cpython-313.pyc
                            [FILE] _copy.cpython-313.pyc
                            [FILE] _errors.cpython-313.pyc
                            [FILE] _info.cpython-313.pyc
                            [FILE] _osfs.cpython-313.pyc
                            [FILE] _path.cpython-313.pyc
                            [FILE] _subfs.cpython-313.pyc
                            [FILE] _tempfs.cpython-313.pyc
                            [FILE] _tools.cpython-313.pyc
                            [FILE] _walk.cpython-313.pyc
                            [FILE] _zipfs.cpython-313.pyc
                            [FILE] __init__.cpython-313.pyc
                    [FILE] fixedTools.py
                    [FILE] intTools.py
                    [FILE] iterTools.py
                    [FILE] lazyTools.py
                    [FILE] loggingTools.py
                    [FILE] macCreatorType.py
                    [FILE] macRes.py
                    [DIR]  plistlib
                        [FILE] py.typed
                        [FILE] __init__.py
                        [DIR]  __pycache__
                            [FILE] __init__.cpython-313.pyc
                    [FILE] psCharStrings.py
                    [FILE] psLib.py
                    [FILE] psOperators.py
                    [FILE] py23.py
                    [FILE] roundTools.py
                    [FILE] sstruct.py
                    [FILE] symfont.py
                    [FILE] testTools.py
                    [FILE] textTools.py
                    [FILE] timeTools.py
                    [FILE] transform.py
                    [FILE] treeTools.py
                    [FILE] vector.py
                    [FILE] visitor.py
                    [FILE] xmlReader.py
                    [FILE] xmlWriter.py
                    [FILE] __init__.py
                    [DIR]  __pycache__
                        [FILE] arrayTools.cpython-313.pyc
                        [FILE] bezierTools.cpython-313.pyc
                        [FILE] classifyTools.cpython-313.pyc
                        [FILE] cliTools.cpython-313.pyc
                        [FILE] configTools.cpython-313.pyc
                        [FILE] cython.cpython-313.pyc
                        [FILE] dictTools.cpython-313.pyc
                        [FILE] eexec.cpython-313.pyc
                        [FILE] encodingTools.cpython-313.pyc
                        [FILE] enumTools.cpython-313.pyc
                        [FILE] etree.cpython-313.pyc
                        [FILE] filenames.cpython-313.pyc
                        [FILE] fixedTools.cpython-313.pyc
                        [FILE] intTools.cpython-313.pyc
                        [FILE] iterTools.cpython-313.pyc
                        [FILE] lazyTools.cpython-313.pyc
                        [FILE] loggingTools.cpython-313.pyc
                        [FILE] macCreatorType.cpython-313.pyc
                        [FILE] macRes.cpython-313.pyc
                        [FILE] psCharStrings.cpython-313.pyc
                        [FILE] psLib.cpython-313.pyc
                        [FILE] psOperators.cpython-313.pyc
                        [FILE] py23.cpython-313.pyc
                        [FILE] roundTools.cpython-313.pyc
                        [FILE] sstruct.cpython-313.pyc
                        [FILE] symfont.cpython-313.pyc
                        [FILE] testTools.cpython-313.pyc
                        [FILE] textTools.cpython-313.pyc
                        [FILE] timeTools.cpython-313.pyc
                        [FILE] transform.cpython-313.pyc
                        [FILE] treeTools.cpython-313.pyc
                        [FILE] vector.cpython-313.pyc
                        [FILE] visitor.cpython-313.pyc
                        [FILE] xmlReader.cpython-313.pyc
                        [FILE] xmlWriter.cpython-313.pyc
                        [FILE] __init__.cpython-313.pyc
                [DIR]  mtiLib
                    [FILE] __init__.py
                    [FILE] __main__.py
                    [DIR]  __pycache__
                        [FILE] __init__.cpython-313.pyc
                        [FILE] __main__.cpython-313.pyc
                [DIR]  otlLib
                    [FILE] builder.py
                    [FILE] error.py
                    [FILE] maxContextCalc.py
                    [DIR]  optimize
                        [FILE] gpos.py
                        [FILE] __init__.py
                        [FILE] __main__.py
                        [DIR]  __pycache__
                            [FILE] gpos.cpython-313.pyc
                            [FILE] __init__.cpython-313.pyc
                            [FILE] __main__.cpython-313.pyc
                    [FILE] __init__.py
                    [DIR]  __pycache__
                        [FILE] builder.cpython-313.pyc
                        [FILE] error.cpython-313.pyc
                        [FILE] maxContextCalc.cpython-313.pyc

In [4]:
import os

file_path = r"C:\Users\Yosef Maregn\Desktop\fraud-detection\data\processed\fraud_data_processed.csv"
if os.path.exists(file_path):
    print("File exists ✅")
else:
    print("File not found ❌. Please check the path or create the processed CSV first.")

File exists ✅

In [6]:
import os
print(os.getcwd())

c:\Users\Yosef Maregn\Desktop\fraud-detection\notebooks

In [7]:
import os
print(os.path.exists("data/processed/fraud_data_processed.csv"))

False

In [8]:
import os
print(os.getcwd())

c:\Users\Yosef Maregn\Desktop\fraud-detection\notebooks

In [9]:
import pandas as pd

df = pd.read_csv("../data/processed/fraud_data_processed.csv")

df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151112 entries, 0 to 151111
Data columns (total 20 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   user_id            151112 non-null  int64
 1   signup_time        151112 non-null  object
 2   purchase_time      151112 non-null  object
 3   purchase_value     151112 non-null  float64
 4   device_id          151112 non-null  object
 5   age                151112 non-null  float64
 6   ip_address         151112 non-null  float64
 7   class              151112 non-null  int64
 8   ip_int             151112 non-null  int64
 9   time_since_signup  151112 non-null  float64
 10  hour_of_day        151112 non-null  int64
 11  day_of_week        151112 non-null  int64
 12  transaction_count  151112 non-null  float64
 13  sex_M              151112 non-null  bool
 14  source_Direct      151112 non-null  bool
 15  source_SEO         151112 non-null  bool
 16  browser_FireFox    151112 non-null  bool
 17  browser_IE         151112 non-null  bool
 18  browser_Opera      151112 non-null  bool
 19  browser_Safari     151112 non-null  bool
dtypes: bool(7), float64(5), int64(5), object(3)
memory usage: 16.0+ MB

In [10]:
import os

print(os.getcwd())
print(os.path.exists("../data/processed/fraud_data_processed.csv"))

c:\Users\Yosef Maregn\Desktop\fraud-detection\notebooks
True

In [11]:
# Target
y = df["class"]

# Features
X = df.drop(columns=["class"])

In [12]:
import pandas as pd
import os

# Confirm current working directory
print("Current directory:", os.getcwd())

# Load processed dataset
df = pd.read_csv("../data/processed/fraud_data_processed.csv")

# Verify load
print("CSV loaded successfully!")
print(df.shape)

df.head()

Current directory: c:\Users\Yosef Maregn\Desktop\fraud-detection\notebooks
CSV loaded successfully!
(151112, 20)

,user_id,signup_time,purchase_time,purchase_value,device_id,age,ip_address,class,ip_int,time_since_signup,hour_of_day,day_of_week,transaction_count,sex_M,source_Direct,source_SEO,browser_FireFox,browser_IE,browser_Opera,browser_Safari
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,-0.160204,QVPSPJUOCKZAR,0.679914,7.327584e+08,0,0,-0.136057,2,5,0.0,True,False,True,False,False,False,False
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,-1.142592,EOGFQPIZPYXFZ,2.304476,3.503114e+08,0,0,-1.571877,1,0,0.0,False,False,False,False,False,False,False
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,-1.197169,YSSKYOSJHPPLJ,2.304476,2.621474e+09,1,0,-1.577617,18,3,0.0,True,False,True,False,False,True,False
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,0.385567,ATGTXKYKUDUQN,0.911994,3.840542e+09,0,0,-1.420213,13,0,0.0,True,False,True,False,False,False,True
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,0.112681,NAUITBZFJKHWW,1.376155,4.155831e+08,0,0,-0.182509,18,2,0.0,True,False,False,False,False,False,True

In [13]:
# Drop non-model features
X = df.drop(columns=[
    "class",           # target
    "signup_time",     # datetime string
    "purchase_time",   # datetime string
    "device_id",       # high-cardinality identifier
    "ip_address"       # raw IP not useful for modeling
])

# Target variable
y = df["class"]

print("Features shape:", X.shape)
print("Target distribution:")
print(y.value_counts())

Features shape: (151112, 15)
Target distribution:
class
0    136961
1     14151
Name: count, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Train class distribution:")
print(y_train.value_counts(normalize=True))

print("\nTest class distribution:")
print(y_test.value_counts(normalize=True))

Train class distribution:
class
0    0.906352
1    0.093648
Name: proportion, dtype: float64

Test class distribution:
class
0    0.906363
1    0.093637
Name: proportion, dtype: float64

In [1]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_resampled, y_train_resampled = smote.fit_resample(
    X_train, y_train
)

print("Before SMOTE:")
print(y_train.value_counts())

print("\nAfter SMOTE:")
print(y_train_resampled.value_counts())

NameError: name 'X_train' is not defined

In [2]:
# Target variable
y = df["class"]

# Features (drop target and non-numeric / leakage columns)
X = df.drop(columns=[
    "class",
    "signup_time",
    "purchase_time",
    "device_id"
])

NameError: name 'df' is not defined

In [3]:
import pandas as pd

# Load processed dataset (run this EVERY time you restart kernel)
df = pd.read_csv("../data/processed/fraud_data_processed.csv")

# Verify
print(df.shape)
df.head()

(151112, 20)

,user_id,signup_time,purchase_time,purchase_value,device_id,age,ip_address,class,ip_int,time_since_signup,hour_of_day,day_of_week,transaction_count,sex_M,source_Direct,source_SEO,browser_FireFox,browser_IE,browser_Opera,browser_Safari
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,-0.160204,QVPSPJUOCKZAR,0.679914,7.327584e+08,0,0,-0.136057,2,5,0.0,True,False,True,False,False,False,False
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,-1.142592,EOGFQPIZPYXFZ,2.304476,3.503114e+08,0,0,-1.571877,1,0,0.0,False,False,False,False,False,False,False
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,-1.197169,YSSKYOSJHPPLJ,2.304476,2.621474e+09,1,0,-1.577617,18,3,0.0,True,False,True,False,False,True,False
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,0.385567,ATGTXKYKUDUQN,0.911994,3.840542e+09,0,0,-1.420213,13,0,0.0,True,False,True,False,False,False,True
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,0.112681,NAUITBZFJKHWW,1.376155,4.155831e+08,0,0,-0.182509,18,2,0.0,True,False,False,False,False,False,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151112 entries, 0 to 151111
Data columns (total 20 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   user_id            151112 non-null  int64
 1   signup_time        151112 non-null  object
 2   purchase_time      151112 non-null  object
 3   purchase_value     151112 non-null  float64
 4   device_id          151112 non-null  object
 5   age                151112 non-null  float64
 6   ip_address         151112 non-null  float64
 7   class              151112 non-null  int64
 8   ip_int             151112 non-null  int64
 9   time_since_signup  151112 non-null  float64
 10  hour_of_day        151112 non-null  int64
 11  day_of_week        151112 non-null  int64
 12  transaction_count  151112 non-null  float64
 13  sex_M              151112 non-null  bool
 14  source_Direct      151112 non-null  bool
 15  source_SEO         151112 non-null  bool
 16  browser_FireFox    151112 non-null  bool
 17  browser_IE         151112 non-null  bool
 18  browser_Opera      151112 non-null  bool
 19  browser_Safari     151112 non-null  bool
dtypes: bool(7), float64(5), int64(5), object(3)
memory usage: 16.0+ MB

In [5]:
# Target
y = df["class"]

# Features
X = df.drop(columns=[
    "class",
    "signup_time",
    "purchase_time",
    "device_id"
])

In [1]:
from sklearn.model_selection import train_test_split

# Target and features (repeat-safe)
y = df["class"]
X = df.drop(columns=[
    "class",
    "signup_time",
    "purchase_time",
    "device_id"
])

# Stratified split (VERY important for imbalance)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train class distribution:")
print(y_train.value_counts(normalize=True))

print("\nTest class distribution:")
print(y_test.value_counts(normalize=True))

NameError: name 'df' is not defined

In [2]:
import pandas as pd

# Load processed dataset
df = pd.read_csv("../data/processed/fraud_data_processed.csv")

# Verify load
df.head(), df.shape

(   user_id          signup_time        purchase_time  purchase_value  \
 0    22058  2015-02-24 22:55:49  2015-04-18 02:47:11       -0.160204
 1   333320  2015-06-07 20:39:50  2015-06-08 01:38:54       -1.142592
 2     1359  2015-01-01 18:52:44  2015-01-01 18:52:45       -1.197169
 3   150084  2015-04-28 21:13:25  2015-05-04 13:54:50        0.385567
 4   221365  2015-07-21 07:09:52  2015-09-09 18:40:53        0.112681

        device_id       age    ip_address  class  ip_int  time_since_signup  \
 0  QVPSPJUOCKZAR  0.679914  7.327584e+08      0       0          -0.136057
 1  EOGFQPIZPYXFZ  2.304476  3.503114e+08      0       0          -1.571877
 2  YSSKYOSJHPPLJ  2.304476  2.621474e+09      1       0          -1.577617
 3  ATGTXKYKUDUQN  0.911994  3.840542e+09      0       0          -1.420213
 4  NAUITBZFJKHWW  1.376155  4.155831e+08      0       0          -0.182509

    hour_of_day  day_of_week  transaction_count  sex_M  source_Direct  \
 0            2            5                0.0   True          False
 1            1            0                0.0  False          False
 2           18            3                0.0   True          False
 3           13            0                0.0   True          False
 4           18            2                0.0   True          False

    source_SEO  browser_FireFox  browser_IE  browser_Opera  browser_Safari
 0        True            False       False          False           False
 1       False            False       False          False           False
 2        True            False       False           True           False
 3        True            False       False          False            True
 4       False            False       False          False            True  ,
 (151112, 20))

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151112 entries, 0 to 151111
Data columns (total 20 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   user_id            151112 non-null  int64
 1   signup_time        151112 non-null  object
 2   purchase_time      151112 non-null  object
 3   purchase_value     151112 non-null  float64
 4   device_id          151112 non-null  object
 5   age                151112 non-null  float64
 6   ip_address         151112 non-null  float64
 7   class              151112 non-null  int64
 8   ip_int             151112 non-null  int64
 9   time_since_signup  151112 non-null  float64
 10  hour_of_day        151112 non-null  int64
 11  day_of_week        151112 non-null  int64
 12  transaction_count  151112 non-null  float64
 13  sex_M              151112 non-null  bool
 14  source_Direct      151112 non-null  bool
 15  source_SEO         151112 non-null  bool
 16  browser_FireFox    151112 non-null  bool
 17  browser_IE         151112 non-null  bool
 18  browser_Opera      151112 non-null  bool
 19  browser_Safari     151112 non-null  bool
dtypes: bool(7), float64(5), int64(5), object(3)
memory usage: 16.0+ MB

In [4]:
from sklearn.model_selection import train_test_split

y = df["class"]
X = df.drop(columns=[
    "class",
    "signup_time",
    "purchase_time",
    "device_id"
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [5]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, average_precision_score

model = LogisticRegression(max_iter=1000)
model.fit(X_train_resampled, y_train_resampled)

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

print("F1:", f1_score(y_test, y_pred))
print("AUC-PR:", average_precision_score(y_test, y_proba))

F1: 0.16109477222255567
AUC-PR: 0.0952628129721176

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, average_precision_score, confusion_matrix

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train_resampled, y_train_resampled)

RandomForestClassifier(max_depth=10, n_estimators=200, n_jobs=-1,
                       random_state=42)

In [8]:
rf_pred = rf.predict(X_test)
rf_proba = rf.predict_proba(X_test)[:, 1]

rf_f1 = f1_score(y_test, rf_pred)
rf_auc_pr = average_precision_score(y_test, rf_proba)

rf_f1, rf_auc_pr

(0.6099518459069021, 0.620714741143756)

In [9]:
confusion_matrix(y_test, rf_pred)

array([[26759,   634],
       [ 1310,  1520]])

In [10]:
import pandas as pd

results = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "F1 Score": [f1_lr, rf_f1],
    "AUC-PR": [auc_pr_lr, rf_auc_pr]
})

results

NameError: name 'f1_lr' is not defined

In [11]:
from sklearn.metrics import f1_score, precision_recall_curve, average_precision_score, confusion_matrix, classification_report

# Example for Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Assuming df is already loaded and preprocessed
X = df.drop(columns=['class'])
y = df['class']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Train Logistic Regression
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)

# Make predictions
y_pred = lr_model.predict(X_test)

# Compute metrics
f1_lr = f1_score(y_test, y_pred)
print("F1-score Logistic Regression:", f1_lr)

ValueError: could not convert string to float: '2015-07-17 16:58:56'

In [12]:
X = df.drop(columns=['class', 'signup_time', 'purchase_time'])
y = df['class']

In [13]:
non_numeric_cols = X.select_dtypes(exclude='number').columns
print(non_numeric_cols)

Index(['device_id', 'sex_M', 'source_Direct', 'source_SEO', 'browser_FireFox',
       'browser_IE', 'browser_Opera', 'browser_Safari'],
      dtype='object')

In [14]:
X = df.drop(columns=['class', 'device_id'])
y = df['class']

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, precision_recall_curve, auc

model = LogisticRegression(max_iter=1000)
model.fit(X_train_res, y_train_res)

y_pred = model.predict(X_test)
f1_lr = f1_score(y_test, y_pred)
print("F1-score Logistic Regression:", f1_lr)

NameError: name 'X_train_res' is not defined

In [17]:
# Drop non-numeric ID column
X = df.drop(columns=['class', 'device_id'])
y = df['class']

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [19]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("Before SMOTE:", y_train.value_counts())
print("After SMOTE:", y_train_res.value_counts())

ValueError: could not convert string to float: '2015-07-17 16:58:56'

In [20]:
X = df.drop(columns=['class', 'device_id', 'signup_time', 'purchase_time'])
y = df['class']

In [21]:
# Convert to datetime
df['signup_time'] = pd.to_datetime(df['signup_time'])
df['purchase_time'] = pd.to_datetime(df['purchase_time'])

# Create numeric features
df['signup_timestamp'] = df['signup_time'].astype(int) // 10**9  # seconds since epoch
df['purchase_timestamp'] = df['purchase_time'].astype(int) // 10**9

In [22]:
X = df.drop(columns=['class', 'device_id', 'signup_time', 'purchase_time'])
y = df['class']

In [23]:
# Task 2: Preprocessing + SMOTE + Logistic Regression
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# 1. Load the processed dataset
df = pd.read_csv("data/processed/fraud_data_processed.csv")

# 2. Convert datetime columns to numeric if still present
df['signup_time'] = pd.to_datetime(df['signup_time'])
df['purchase_time'] = pd.to_datetime(df['purchase_time'])
df['signup_timestamp'] = df['signup_time'].astype(int) // 10**9
df['purchase_timestamp'] = df['purchase_time'].astype(int) // 10**9

# 3. Prepare features and target
X = df.drop(columns=['class', 'device_id', 'signup_time', 'purchase_time'])
y = df['class']

# 4. Split data (stratified)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 5. Scale numerical features
num_cols = X.select_dtypes(include=['float64', 'int64']).columns
scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

# 6. Handle class imbalance with SMOTE
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# 7. Train Logistic Regression
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train_res, y_train_res)

# 8. Evaluate
y_pred = model.predict(X_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/fraud_data_processed.csv'

In [25]:
import pandas as pd

# Load the processed dataset
df = pd.read_csv("data/processed/fraud_data_processed.csv")

# Quick check
print(df.head())
print(df.info())

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/fraud_data_processed.csv'

In [31]:
# ========================
# Task 2: Model Training
# ========================

import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, precision_recall_curve, auc, confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE

# ------------------------
# 1. Load processed dataset
# ------------------------
df = pd.read_csv("../data/processed/fraud_data_processed.csv")

# ------------------------
# 2. Define features and target
# ------------------------
target_col = 'class'
X = df.drop(columns=['user_id', 'signup_time', 'purchase_time', 'ip_address', target_col])
y = df[target_col]

# ------------------------
# 3. Train-test split (stratified)
# ------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ------------------------
# 4. Scale numerical features
# ------------------------
num_cols = X_train.select_dtypes(include=['float64', 'int64']).columns
scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

# ------------------------
# 5. Handle class imbalance with SMOTE
# ------------------------
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("Class distribution after SMOTE:")
print(pd.Series(y_train_res).value_counts())

# ------------------------
# 6. Train Logistic Regression (baseline)
# ------------------------
lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train_res, y_train_res)
y_pred_lr = lr.predict(X_test)

f1_lr = f1_score(y_test, y_pred_lr)
print("Logistic Regression F1-score:", f1_lr)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

# ------------------------
# 7. Train Random Forest
# ------------------------
rf = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42, n_jobs=-1)
rf.fit(X_train_res, y_train_res)
y_pred_rf = rf.predict(X_test)

f1_rf = f1_score(y_test, y_pred_rf)
print("Random Forest F1-score:", f1_rf)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

# ------------------------
# 8. Optional: Cross-validation
# ------------------------
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(rf, X_train_res, y_train_res, cv=skf, scoring='f1')
print("Random Forest 5-fold CV F1-scores:", cv_scores)
print("Mean CV F1:", cv_scores.mean())

ValueError: could not convert string to float: 'XVRUVPTHWQASG'

In [28]:
X = df.drop(columns=['user_id', 'device_id', 'signup_time', 'purchase_time', 'class'])
y = df['class']

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [30]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/fraud_data_processed.csv")

df.shape

(151112, 20)

In [2]:
from sklearn.model_selection import train_test_split

# Drop non-numeric / identifier columns
X = df.drop(columns=[
    "class",
    "user_id",
    "device_id",
    "signup_time",
    "purchase_time"
])

y = df["class"]

X.shape, y.shape

((151112, 15), (151112,))

In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

y_train.value_counts(normalize=True), y_test.value_counts(normalize=True)

(class
 0    0.906352
 1    0.093648
 Name: proportion, dtype: float64,
 class
 0    0.906363
 1    0.093637
 Name: proportion, dtype: float64)

In [5]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# sanity check
X_train_res.shape, y_train_res.value_counts()

((219136, 15),
 class
 0    109568
 1    109568
 Name: count, dtype: int64)

In [6]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

lr.fit(X_train_res, y_train_res)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [7]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train_res, y_train_res)

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_split=5, n_estimators=200, n_jobs=-1,
                       random_state=42)

In [8]:
from sklearn.metrics import (
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix
)

y_pred_rf = rf.predict(X_test)
y_proba_rf = rf.predict_proba(X_test)[:, 1]

f1_rf = f1_score(y_test, y_pred_rf)
roc_rf = roc_auc_score(y_test, y_proba_rf)
pr_rf = average_precision_score(y_test, y_proba_rf)

f1_rf, roc_rf, pr_rf

(0.6255161023947151, 0.7672536405382768, 0.6210225970406045)

In [9]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_f1 = cross_val_score(
    rf, X_train_res, y_train_res,
    scoring="f1",
    cv=cv,
    n_jobs=-1
)

cv_f1.mean(), cv_f1.std()

(np.float64(0.8299142086735886), np.float64(0.0018661362710381511))

In [11]:
from sklearn.metrics import f1_score, roc_auc_score, average_precision_score

# Logistic Regression predictions
y_pred_lr = lr.predict(X_test)
y_proba_lr = lr.predict_proba(X_test)[:, 1]

# Store metrics (IMPORTANT)
f1_lr = f1_score(y_test, y_pred_lr)
roc_lr = roc_auc_score(y_test, y_proba_lr)
pr_lr = average_precision_score(y_test, y_proba_lr)

f1_lr, roc_lr, pr_lr

(0.0, 0.5053620647197918, 0.09344315093019745)

In [12]:
import pandas as pd

results = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "F1 Score": [f1_lr, f1_rf],
    "ROC-AUC": [roc_lr, roc_rf],
    "PR-AUC": [pr_lr, pr_rf]
})

results

                 Model  F1 Score   ROC-AUC    PR-AUC
0  Logistic Regression  0.000000  0.505362  0.093443
1        Random Forest  0.625516  0.767254  0.621023